main/urls.py
from django.urls import path

from main import views

urlpatterns = [
    path("", views.CreateEntry.as_view(), name="index"),
    path("submit-success/", views.submit_success, name="submit_success"),
    path("verify-success/", views.verify_success, name="verify_success"),
    path("about/", views.about, name="about"),
    path("privacy/", views.privacy, name="privacy"),
]

popoff/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("dja/", admin.site.urls),
    path("", include("main.urls")),
]

z01/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("dja/", admin.site.urls),
    path("", include("main.urls")),
]

zima/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("dja/", admin.site.urls),
    path("", include("main.urls")),
]

main/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    first_name = None
    last_name = None
    email = models.EmailField(
        blank=True,
        null=True,
        unique=True,
    )


class Entry(models.Model):
    verify_key = models.UUIDField(default=uuid.uuid4, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    terms = models.BooleanField(default=False)
    email = models.EmailField()
    contact = models.CharField(max_length=300)
    resource = models.URLField()
    has_received = models.ManyToManyField("Entry", through="Matching")
    is_verified = models.BooleanField(default=False)
    is_approved = models.BooleanField(default=False)

    def __str__(self):
        ret = f"[{self.id}]"
        if len(self.contact) > 20:
            ret += f"({self.contact[:20]}...)"
        else:
            ret += f"({self.contact})"
        if len(self.resource) > 25:
            ret += f"({self.resource[:25]}...)"
        return ret

    class Meta:
        verbose_name_plural = "Entries"


class Matching(models.Model):
    person_who_received = models.ForeignKey(
        Entry,
        on_delete=models.CASCADE,
        related_name="informed_entry",
    )
    person_who_was_received = models.ForeignKey(
        Entry,
        on_delete=models.CASCADE,
        related_name="content_entry",
    )
    created_at = models.DateTimeField(auto_now_add=True)


class Matchlog(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    receiver = models.ForeignKey(Entry, on_delete=models.CASCADE)

main/views.py
from django.conf import settings
from django.core.mail import mail_admins, send_mail
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

from main import models


class CreateEntry(CreateView):
    model = models.Entry
    fields = ["email", "contact", "resource", "terms"]
    template_name = "main/index.html"

    def notify_admin(self):
        mail_admins(
            f"admin: new entry: {self.object.resource}",
            render_to_string(
                "main/admin_email.txt",
                {
                    "email": self.object.email,
                    "resource": self.object.resource,
                    "contact": self.object.contact,
                    "canonical_url": settings.CANONICAL_URL,
                },
            ),
        )

    def form_valid(self, form):
        if not form.cleaned_data.get("terms", False):
            form.add_error(
                "terms", "we’d love to but cannot proceed unless this is fine"
            )
            return super().form_invalid(form)

        self.object = form.save()
        url = f"{settings.CANONICAL_URL}{reverse_lazy('verify_success')}"
        url += f"?key={str(self.object.verify_key)}"
        subject = f"01z: verify email for {self.object.resource}"
        content = render_to_string(
            "main/welcome_email.txt",
            {
                "email": self.object.email,
                "resource": self.object.resource,
                "contact": self.object.contact,
                "verify_url": url,
            },
        )
        send_mail(subject, content, settings.DEFAULT_FROM_EMAIL, [self.object.email])
        self.notify_admin()
        return super().form_valid(form)

    def get_success_url(self):
        url = reverse_lazy("submit_success")
        url += "?key="
        url += str(self.object.verify_key)
        return url


def submit_success(request):
    if request.GET.get("key") is not None:
        return render(request, "main/submit_success.html")
    else:
        return redirect("index")


def verify_success(request):
    if request.GET.get("key") is not None:
        entry = get_object_or_404(
            models.Entry,
            verify_key=request.GET.get("key"),
        )
        entry = models.Entry.objects.get(verify_key=request.GET.get("key"))
        entry.is_verified = True
        entry.save()
        return render(request, "main/verify_success.html", {"email": entry.email})
    else:
        return redirect("index")


def about(request):
    return render(request, "main/about.html")


def privacy(request):
    return render(request, "main/privacy.html")

main/templates/main/about.html
{% extends 'main/layout.html' %}

{% block content %}
<main>
    <h1><a href="/">01z.co</a></h1>
    <p>
        <strong>about</strong>
    </p>
    <p>
        Directly inspired by Ivan Illich’s book <i>Deschooling Society</i>.
    </p>
    <p>
        We do not assume responsibility for whatever links or text or data of any kind
        we distribute to subscribers.
    </p>
    <p>
        We do not assume responsibility for past or future behaviour of any user that
        uses our website to meet people.
    </p>
    <p>
        However, we conduct some moderation on submissions. Specifically:
    </p>
    <ul>
        <li>we perform link-based email verification</li>
        <li>we delete garbage data entries</li>
        <li>we ban users who have exhibited problematic behaviour</li>
    </ul>
    <p>
        If your interaction with someone from a list we sent you was problematic in any
        way, please let us know at
        <a href="mailto:admin+abuse@01z.co">admin+abuse@01z.co</a>.
    </p>
    <p>
        This website’s source code is open for everyone to read and deploy and improve.
        The project is developed on the open internet at
        <a href="https://github.com/sirodoht/zima">github.com/sirodoht/zima</a>.
    </p>
</main>
{% endblock %}

main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block content %}
<main>
    <h1><a href="/">01z.co</a></h1>
    <p>
        <strong>meet people based on intellectual interests</strong>
    </p>
    <p>
        In his 1971 book, Ivan Illich envisions a system from the future, with which
        intellectual matches between people happen in large cities. This is an
        implementation of that system.
    </p>
    <form method="post">
        <p>
            To use:
        </p>

        <p style="padding-left: 16px;">
            1. Enter your email address, in which we will send the list of people
            interested in the same thing as you. This email address will remain private
            and will not be shared with anyone else.
        </p>
        {{ form.email.errors }}
        <p style="padding-left: 16px;">
            <input type="email" name="email" required id="id_email" placeholder="email address">
            <br><small>(private email — how we contact you)</small>
        </p>

        <p style="padding-left: 16px;">
            2. Enter a way for other people to get in touch with you. This could be an
            email address (the same or different than the one above) or a phone number
            or some other way. It has to be personal, ie. not corresponding to
            something that belongs to the group or is public.
        </p>
        <p style="padding-left: 16px;">
            This email address will be shared with people interested in the same thing
            as you.
        </p>
        {{ form.contact.errors }}
        <p style="padding-left: 16px;">
            <input type="text" name="contact" maxlength="300" required id="id_contact" placeholder="email address or phone">
            <br><small>(distributed email — how others contact you)</small>
        </p>

        <p style="padding-left: 16px;">
            3. Enter a link which contains or presents or talks about a book, an article, a
            film, a podcast episode on which you seek a partner for discussion.
        </p>
        {{ form.resource.errors }}
        <p style="padding-left: 16px;">
            <input type="url" name="resource" required id="id_resource" placeholder="https://...">
            <br><small>(thing of interest)</small>
        </p>

        <p style="padding-left: 16px;">
            4. Click this checkbox to signify your agreement (a) that it is not our
            responsibility if the data we send you are problematic in any way and (b)
            that if you meet someone through 01z.co it is not our responsibility if
            their behaviour is problematic in any way.
        </p>
        {{ form.terms.errors }}
        <p style="padding-left: 16px;">
            <input type="checkbox" name="terms" required id="id_terms">
            <label for="id_terms">Fine.</label>
            <br><small>(we cannot proceed unless this is fine)</small>
        </p>

        {{ form.non_field_errors }}
        <p style="padding-left: 16px;">
            <input type="submit" value="Submit">
        </p>

        <p>
            Within a few days, you will receive a list of people (their names and ways
            to contact them) who have taken the same initiative. This list will enable
            you to contact them in order to arrange a meeting (online or offline) with
            persons for which they are exclusively known to you by the fact that they
            requested a dialogue about the same subject.
        </p>
        <p>
            To clarify: we cannot guarantee that there are people who have taken the
            same initiative as you. In case there aren’t, we will not get in touch.
        </p>
    </form>

    <hr>
    <p>
        <a href="{% url 'about' %}">about</a>
        / <a href="{% url 'privacy' %}">data privacy</a>
    </p>
</main>
{% endblock %}

main/templates/main/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}01z.co — meet people based on intellectual interests{% endblock %}</title>
        <meta name="description" content="meet people based on intellectual interests">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body { font-family: sans-serif; line-height: 1.5; }
            h1 { margin: 0; }
            a { color: black; }
            main { max-width: 500px; }
            blockquote { margin: 0; padding-left: 16px; border-left: 8px solid aquamarine; }
            hr { border: none; border-top: 1px solid gray; }
            .errorlist { color: red; }
        </style>
    </head>
    <body>
        {% if messages %}
        <aside>
            {% for message in messages %}
            <div {% if message.tags %}class="alert-{{ message.tags }}"{% endif %}>{{ message|safe }}</div>
            {% endfor %}
        </aside>
        {% endif %}

        {% block content %}
        {% endblock %}
    </body>
</html>

main/templates/main/privacy.html
{% extends 'main/layout.html' %}

{% block content %}
<main>
    <h1><a href="/">01z.co</a></h1>
    <p>
        <strong>data privacy</strong>
    </p>
    <p>
        This website does not implement any of the following:
    </p>
    <ul>
        <li>
            tracking of user or visitor behaviour
        </li>
        <li>
            sale of user or visitor data
        </li>
        <li>
            sharing user or visitor data with any third parties
        </li>
        <li>
            ads
        </li>
        <li>
            authentication for non-admins
        </li>
        <li>
            cookies of any kind
        </li>
    </ul>
    <p>
        This website is served from servers located in Germany.
    </p>
    <p>
        This website’s source code is publicy auditable at
        <a href="https://github.com/sirodoht/zima">github.com/sirodoht/zima</a>.
    </p>
</main>
{% endblock %}

main/templates/main/submit_success.html
{% extends 'main/layout.html' %}

{% block content %}
<main>
    <h1><a href="/">01z.co</a></h1>
    <p>
        <strong>thank you + check mail</strong>
    </p>
    <p>
        Your information has been submitted.
    </p>
    <p>
        Please <strong>check your email</strong> (the private email address you entered in the
        first step) to process with the next steps.
    </p>
    <blockquote>
        <p>
            “Creative, exploratory learning requires peers currently puzzled about the
            same terms or problems.”
        </p>
        <footer>—Ivan Illich, <cite>Deschooling Society</cite>, 1971</footer>
    </blockquote>
</main>
{% endblock %}

main/templates/main/verify_success.html
{% extends 'main/layout.html' %}

{% block content %}
<main>
    <h1><a href="/">01z.co</a></h1>
    <p>
        <strong>email verified! thanks {{ email }}</strong>
    </p>
    <p>
        Your information has been submitted and your email has been verified.
    </p>
    <p>
        Within a few days, you will receive a list of people (their names and ways to
        contact them) that are interested in the same thing of interest as you.
    </p>
    <p>
        Of course, it is also probable that nobody else has declared to us their
        interest to the thing of interest that you have. In that case, we will take no
        action.
    </p>
    <blockquote style="border-color: chocolate;">
        <p>
            “At a first meeting in a coffee shop, say, the partners might establish their
            identities by placing the book under discussion next to their cups.”
        </p>
        <footer>—Ivan Illich, <cite>Deschooling Society</cite>, 1971</footer>
    </blockquote>
</main>
{% endblock %}